### ISSUE TITLE
Dialogue, cutscene or videos dont work

### ISSUE THREAD

**Issue by XTihX1** [MemeHoovy/FNF-PsychEngine-Extra-1#3]
### Describe your bug here.

ye, it's only in this engine that this happens because I've tried it in other engines and it works perfectly and the problem is that the countdown doesn't stop for the dialogue or cutscene to happen, I was wondering if anyone has any idea why.

Here's a video showing what I'm talking about.
https://user-images.githubusercontent.com/95257883/195620724-f016a123-4605-4cf1-9d1c-07bc0cacffa7.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHoovy** [comment]
there's many different lua modifications that were implemented by Starmapo, that is likely to being causing the issue to occur, not to mention, this runs on 0.6.2 so old lua scripts might not work

**Comment by XTihX1** [comment]
hmmmm, thanks.
